version: '3.8'

services:
  inference:
    build:
      context: .
      dockerfile: Dockerfile.inference
    ports:
      - "8000:8000"
    container_name: inference-app

  interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    ports:
      - "7860:7860"
    container_name: interface-app
